Repository commercelayer/app-returns, pull requests merged in 2024-04, with the labels that each got.

#11 Update all deps to latest major
  package.json
  packages/app/package.json
  packages/app/src/components/FormFieldItems.tsx
  packages/app/src/components/ListItemReturn.tsx
  packages/app/src/components/ReturnInfo.tsx
  packages/app/src/pages/Home.tsx
  packages/app/tsconfig.json
  packages/app/vite.config.mts
  pnpm-lock.yaml
Labels: enhancement

#12 v1.2.1
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#14 v1.2.2
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#13 Show return detail actions only with correct permissions
  package.json
  packages/app/package.json
  packages/app/src/components/ReturnInfo.tsx
  packages/app/src/components/ReturnSummary.tsx
  pnpm-lock.yaml
Labels: bug

#15 v1.2.3
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#16 Update app-elements
  packages/app/package.json
  pnpm-lock.yaml
Labels: enhancement

#17 v1.2.4
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#19 v1.2.5
  lerna.json
  packages/app/package.json
  pnpm-lock.yaml
Labels: ignore-for-release
